# Generated by Django 5.2.7 on 2025-11-24 07:13

from django.db import migrations


def create_delivery_type(apps, schema_editor):
    DeliveryType = apps.get_model('orders', 'DeliveryType')

    if not DeliveryType.objects.exists():
        DeliveryType.objects.create(
            cost_ordinary_delivery=200.00,
            cost_express_delivery=500.00,
            min_cost_order_by_free_delivery=2000.00
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_delivery_type
        )
    ]

