# Generated by Django 5.2.7 on 2025-10-30 08:31

from django.db import migrations
from django.conf import settings


def create_admin_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    if not User.objects.filter(username='admin').exists():
        # Создаём, если нет
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='admin'
        )
    else:
        # Восстанавливаем, если был удалён
        User.objects.filter(username='admin').update(is_deleted=False)


def reverse_create_admin_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    # Мягкое удаление — помечаем как удалённого
    User.objects.filter(username='admin').update(is_deleted=True)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_admin_user,
            reverse_code=reverse_create_admin_user,
        ),
    ]
