# Generated by Django 5.2.7 on 2025-10-24 09:12

from django.db import migrations
from django.conf import settings


def create_admin_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='admin'
        )


def reverse_create_admin_user(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_admin_user,
            reverse_code=reverse_create_admin_user,
        ),
    ]
